# Generated by Django 2.0 on 2019-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('sex', models.SmallIntegerField()),
                ('age', models.BigIntegerField()),
                ('logintime', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
