# Generated by Django 2.0 on 2019-03-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('state', models.SmallIntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradesign.Users')),
            ],
            options={
                'db_table': 'Notice',
            },
        ),
    ]
