# Generated by Django 2.0 on 2019-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesign', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='color',
            field=models.CharField(default='layui-bg-red', max_length=100),
        ),
    ]
